# Generated by Django 2.2.13 on 2021-03-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarea',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='tarea_maestros'),
        ),
    ]
