# Generated by Django 2.2.13 on 2021-03-09 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210304_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarea_estudinate',
            name='fecha_entregado',
        ),
    ]
