from .profile import Profile
from .users import User
from .estudiante import Estudiante
from .profesion import Profesion
from .maestro import Maestro
from .ciclo import Ciclo
from .evento import Evento
from .nivel import Nivel
from .seccion import Seccion
from .grado import Grado
from .curso import Curso
from .asignacion import Asignacion
from .tarea import Tarea
from .tarea_estudiante  import Tarea_Estudinate
from .material import Material
from .rol import Rol