from .user import UserSerializer, UserReadSerializer, ProfileSerializer, ProfileAndUserSerializer,CreateProfileSerializer
from .maestro import MaestroSerializer, CrearMaestroSerializer
from .estudiante import EstudianteSerializer,EstudianteCrearSerializer
